export abstract class Constants {
    // API urls
    static readonly URL_AUTHENTICATE = '/users/authenticate';
    static readonly URL_MENU = '/users/getMenu';
    static readonly URL_REGISTER = '/users/register';
    static readonly URL_USERS = '/users';

    //PAGES
    static readonly PG_ACCOUNTHOME = '/accounthome';
    static readonly PG_HOME = '/home';
    static readonly PG_LOGIN = '/login';
    static readonly PG_REGISTER = '/register';
    static readonly PG_DASHBOARD = '/dashboard';
    static readonly PG_HOMEACCOUNT = '/myaccount';

    // string
    static readonly CURRENTUSER = 'currentUser';

    // roles
    static readonly USER = '1';
    static readonly ADMIN = '2';
    static readonly SUPER = '3';

    // form
    static readonly FIELD_OBJECTS = [
      {
        label: 'First Name',
        controlName: 'firstname',
        value: '',
        type: 'text',
        className: '',
        ngClass:'',
        minLength: '',
        maxLength: '',
        required: true,
        pattern: '',
        disabled: false,
        readonly: false,
        size: 16,
        minDate:'',
        maxDate: '',
        fileType: '',
        placeHolder: '',
        step: 0,
        min: 0,
        max: 10,
        width: 0,
        height: 0,
        autocomplete: 'off',
        rows:0,
        cols:0,
        checked: false,
        labelPosition: 'after',
        dropdownItems:[],
        color: null,
        btnType: 'mat-button',
        href:'',
        target:'',
        icon:'',
        radioControls:[]
      },
      {
        label: 'Last Name',
        controlName: 'lastname',
        value: '',
        type: 'text',
        className: '',
        ngClass:'',
        minLength: '',
        maxLength: '',
        required: false,
        pattern: '',
        disabled: false,
        readonly: false,
        size: 16,
        minDate:'',
        maxDate: '',
        fileType: '',
        placeHolder: '',
        step: 0,
        min: 0,
        max: 10,
        width: 0,
        height: 0,
        autocomplete: 'off',
        rows:0,
        cols:0,
        checked: false,
        labelPosition: 'after',
        dropdownItems:[],
        color: null,
        btnType: 'mat-button',
        href:'',
        target:'',
        icon:'',
        radioControls:[]
      },
      {
        label: 'Gender',
        controlName: 'gender',
        value: '',
        type: 'select',
        className: '',
        ngClass:'',
        minLength: '',
        maxLength: '',
        required: false,
        pattern: '',
        disabled: false,
        readonly: false,
        size: 16,
        minDate:'',
        maxDate: '',
        fileType: '',
        placeHolder: '',
        step: 0,
        min: 0,
        max: 10,
        width: 0,
        height: 0,
        autocomplete: 'off',
        rows:0,
        cols:0,
        checked: false,
        labelPosition: 'after',
        dropdownItems:[{name:'Male', value:'male'}, {name:'Female',  value:'female'}],
        color: null,
        btnType: 'mat-button',
        href:'',
        target:'',
        icon:'',
        radioControls:[]
      },
      {
        label: 'Work',
        controlName: 'work',
        value: '',
        type: 'checkbox',
        className: '',
        ngClass:'',
        minLength: '',
        maxLength: '',
        required: false,
        pattern: '',
        disabled: false,
        readonly: false,
        size: 16,
        minDate:'',
        maxDate: '',
        fileType: '',
        placeHolder: '',
        step: 0,
        min: 0,
        max: 10,
        width: 0,
        height: 0,
        autocomplete: 'off',
        rows:0,
        cols:0,
        checked: false,
        labelPosition: 'after',
        dropdownItems:[],
        color: null,
        btnType: '',
        href:'',
        target:'',
        icon:'',
        radioControls:[]
      },
      {
        label: '',
        controlName: 'genderRadio',
        value: '',
        type: 'radio',
        className: '',
        ngClass:'',
        minLength: '',
        maxLength: '',
        required: false,
        pattern: '',
        disabled: false,
        readonly: false,
        size: 16,
        minDate:'',
        maxDate: '',
        fileType: '',
        placeHolder: '',
        step: 0,
        min: 0,
        max: 10,
        width: 0,
        height: 0,
        autocomplete: 'off',
        rows:0,
        cols:0,
        checked: false,
        labelPosition: 'after',
        dropdownItems:[],
        color: null,
        btnType: '',
        href:'',
        target:'',
        icon:'',
        radioControls:['Male', 'Female']
      },
      {
        label: 'Comments',
        controlName: 'comments',
        value: '',
        type: 'textarea',
        className: '',
        ngClass:'',
        minLength: '',
        maxLength: '',
        required: false,
        pattern: '',
        disabled: false,
        readonly: false,
        size: 16,
        minDate:'',
        maxDate: '',
        fileType: '',
        placeHolder: '',
        step: 0,
        min: 0,
        max: 10,
        width: 0,
        height: 0,
        autocomplete: 'off',
        rows:10,
        cols:20,
        checked: false,
        labelPosition: 'after',
        dropdownItems:[],
        color: null,
        btnType: '',
        href:'',
        target:'',
        icon:'',
        radioControls:[]
      },
      {
        label: 'Submit',
        controlName: '',
        value: '',
        type: 'button',
        className: '',
        ngClass:'',
        minLength: '',
        maxLength: '',
        required: false,
        pattern: '',
        disabled: false,
        readonly: false,
        size: 16,
        minDate:'',
        maxDate: '',
        fileType: '',
        placeHolder: '',
        step: 0,
        min: 0,
        max: 10,
        width: 0,
        height: 0,
        autocomplete: 'off',
        rows:10,
        cols:20,
        checked: false,
        labelPosition: 'after',
        dropdownItems:[],
        color: 'primary',
        btnType: 'mat-icon-button',
        href:'',
        target:'',
        icon:'home',
        radioControls:[]
      }
    ];

    static readonly LOGIN_FORM = [
      {
        label: 'User Name',
        controlName: 'username',
        value: '',
        type: 'text',
        className: '',
        ngClass:'',
        minLength: '',
        maxLength: '',
        required: true,
        pattern: '',
        disabled: false,
        readonly: false,
        size: 16,
        minDate:'',
        maxDate: '',
        fileType: '',
        placeHolder: '',
        step: 0,
        min: 0,
        max: 10,
        width: 0,
        height: 0,
        autocomplete: 'off',
        rows:0,
        cols:0,
        checked: false,
        labelPosition: 'after',
        dropdownItems:[],
        color: null,
        btnType: '',
        href:'',
        target:'',
        icon:'',
        radioControls:[],
        toggleValues: [],
        toggleType:''
      },
      {
        label: 'Password',
        controlName: 'password',
        value: '',
        type: 'password',
        className: '',
        ngClass:'',
        minLength: '',
        maxLength: '',
        required: true,
        pattern: '',
        disabled: false,
        readonly: false,
        size: 16,
        minDate:'',
        maxDate: '',
        fileType: '',
        placeHolder: '',
        step: 0,
        min: 0,
        max: 10,
        width: 0,
        height: 0,
        autocomplete: 'off',
        rows:0,
        cols:0,
        checked: false,
        labelPosition: 'after',
        dropdownItems:[],
        color: null,
        btnType: 'mat-button',
        href:'',
        target:'',
        icon:'',
        radioControls:[],
        toggleValues: [],
        toggleType:''
      },
      {
        label: 'Address',
        controlName: '',
        value: '',
        type: 'formGroupArray',
        className: '',
        ngClass:'',
        minLength: '',
        maxLength: '',
        required: false,
        pattern: '',
        disabled: false,
        readonly: false,
        size: 16,
        minDate:'',
        maxDate: '',
        fileType: '',
        placeHolder: '',
        step: 0,
        min: 0,
        max: 10,
        width: 0,
        height: 0,
        autocomplete: 'off',
        rows:0,
        cols:0,
        checked: false,
        labelPosition: 'after',
        dropdownItems:[],
        color: null,
        btnType: 'mat-button',
        href:'',
        target:'',
        icon:'',
        radioControls:[],
        toggleValues: [],
        toggleType:'',
        formArrayName: 'address',
        formArrayFields: [
          {
            label: 'Address 1',
            controlName: 'add1',
            value: '',
            type: 'text',
            className: '',
            ngClass:'',
            minLength: '',
            maxLength: '',
            required: false,
            pattern: '',
            disabled: false,
            readonly: false,
            size: 16,
            minDate:'',
            maxDate: '',
            fileType: '',
            placeHolder: '',
            step: 0,
            min: 0,
            max: 10,
            width: 0,
            height: 0,
            autocomplete: 'off',
            rows:0,
            cols:0,
            checked: false,
            labelPosition: 'after',
            dropdownItems:[],
            color: null,
            btnType: '',
            href:'',
            target:'',
            icon:'',
            radioControls:[],
            toggleValues: [],
            toggleType:''
          },
          {
            label: 'Address 2',
            controlName: 'add2',
            value: '',
            type: 'text',
            className: '',
            ngClass:'',
            minLength: '',
            maxLength: '',
            required: false,
            pattern: '',
            disabled: false,
            readonly: false,
            size: 16,
            minDate:'',
            maxDate: '',
            fileType: '',
            placeHolder: '',
            step: 0,
            min: 0,
            max: 10,
            width: 0,
            height: 0,
            autocomplete: 'off',
            rows:0,
            cols:0,
            checked: false,
            labelPosition: 'after',
            dropdownItems:[],
            color: null,
            btnType: '',
            href:'',
            target:'',
            icon:'',
            radioControls:[],
            toggleValues: [],
            toggleType:''
          }
        ]
      }
    ];

    static readonly REGISTER_FORM = [
      {
        label: 'First Name',
        controlName: 'firstname',
        value: '',
        type: 'text',
        className: '',
        ngClass:'',
        minLength: '',
        maxLength: '',
        required: true,
        pattern: '',
        disabled: false,
        readonly: false,
        size: 16,
        minDate:'',
        maxDate: '',
        fileType: '',
        placeHolder: '',
        step: 0,
        min: 0,
        max: 10,
        width: 0,
        height: 0,
        autocomplete: 'off',
        rows:0,
        cols:0,
        checked: false,
        labelPosition: 'after',
        dropdownItems:[],
        color: null,
        btnType: '',
        href:'',
        target:'',
        icon:'',
        radioControls:[],
        toggleValues: [],
        toggleType:''
      },
      {
        label: 'Last Name',
        controlName: 'lastname',
        value: '',
        type: 'text',
        className: '',
        ngClass:'',
        minLength: '',
        maxLength: '',
        required: true,
        pattern: '',
        disabled: false,
        readonly: false,
        size: 16,
        minDate:'',
        maxDate: '',
        fileType: '',
        placeHolder: '',
        step: 0,
        min: 0,
        max: 10,
        width: 0,
        height: 0,
        autocomplete: 'off',
        rows:0,
        cols:0,
        checked: false,
        labelPosition: 'after',
        dropdownItems:[],
        color: null,
        btnType: '',
        href:'',
        target:'',
        icon:'',
        radioControls:[],
        toggleValues: [],
        toggleType:''
      },
      {
        label: 'User Name',
        controlName: 'username',
        value: '',
        type: 'text',
        className: '',
        ngClass:'',
        minLength: '',
        maxLength: '',
        required: true,
        pattern: '',
        disabled: false,
        readonly: false,
        size: 16,
        minDate:'',
        maxDate: '',
        fileType: '',
        placeHolder: '',
        step: 0,
        min: 0,
        max: 10,
        width: 0,
        height: 0,
        autocomplete: 'off',
        rows:0,
        cols:0,
        checked: false,
        labelPosition: 'after',
        dropdownItems:[],
        color: null,
        btnType: '',
        href:'',
        target:'',
        icon:'',
        radioControls:[]
      },
      {
        label: 'Password',
        controlName: 'password',
        value: '',
        type: 'password',
        className: '',
        ngClass:'',
        minLength: '',
        maxLength: '',
        required: true,
        pattern: '',
        disabled: false,
        readonly: false,
        size: 16,
        minDate:'',
        maxDate: '',
        fileType: '',
        placeHolder: '',
        step: 0,
        min: 0,
        max: 10,
        width: 0,
        height: 0,
        autocomplete: 'off',
        rows:0,
        cols:0,
        checked: false,
        labelPosition: 'after',
        dropdownItems:[],
        color: null,
        btnType: 'mat-button',
        href:'',
        target:'',
        icon:'',
        radioControls:[]
      }
    ];
  }
